<a href="https://colab.research.google.com/github/kopmean/Zero-to-Mastery-Learn-PyTorch-for-Deep-Learning/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [43]:
# Import torch
import torch

# Create random tensor
X = torch.rand(7,7)
X, X.shape

(tensor([[0.5300, 0.2560, 0.7366, 0.0204, 0.2036, 0.3748, 0.2564],
         [0.3251, 0.0902, 0.3936, 0.6069, 0.1743, 0.4743, 0.8579],
         [0.4486, 0.5139, 0.4569, 0.6012, 0.8179, 0.9736, 0.8175],
         [0.9747, 0.4638, 0.0508, 0.2630, 0.8405, 0.4968, 0.2515],
         [0.1168, 0.0321, 0.0780, 0.3986, 0.7742, 0.7703, 0.0178],
         [0.8119, 0.1087, 0.3943, 0.2973, 0.4037, 0.4018, 0.0513],
         [0.0683, 0.4218, 0.5065, 0.2729, 0.6883, 0.0500, 0.4663]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [45]:
# Create another random tensor
Y = torch.rand(1, 7)
# Perform matrix multiplication
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.0248],
         [1.5690],
         [2.6439],
         [1.7565],
         [1.2670],
         [1.0618],
         [1.2112]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [56]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
X = torch.randn(7,7)
Y = torch.randn(1, 7)

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[ 3.5168],
         [ 2.1984],
         [-1.7815],
         [ 3.8600],
         [-1.5010],
         [-1.6916],
         [-2.9352]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [51]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [62]:
from IPython.lib.display import YouTubeVideo
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device:{device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device:cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [64]:
# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [71]:
# Find max
print(f"Max tensor_C: {torch.max(tensor_C)}")
# Find min
print(f"Min tensor_C: {torch.min(tensor_C)}")

Max tensor_C: 0.5617256760597229
Min tensor_C: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [74]:
# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [80]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors and their shapes
tensor_D.shape, tensor_E.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))